name: Statiq Web Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: Website

    steps:
      - name: Checkout  
        uses: actions/checkout@v3
        with:
          path: Website
          submodules: recursive
          token: ${{ secrets.TOKEN }}
      
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v2  

      - name: Install .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Build Website
        run: dotnet run -- deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
