name: Statiq Web Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages    
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    runs-on: windows-latest

    defaults:
      run:
        working-directory: Website

    steps:
      - name: Checkout  
        uses: actions/checkout@v3
        with:
          path: Website
          submodules: recursive
          token: ${{ secrets.TOKEN }}
      
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v2  

      - name: Install .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Build Website
        run: dotnet run
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload output only
          path: './Website/output'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
